#!/usr/bin/env bash

/Users/aeufemio/projects/digixglobal/ethereum/go-ethereum/build/bin/geth --genesis "mygenesis.json" --datadir "/Users/aeufemio/tmp/.testethereum" --rpc --rpcaddr "localhost" --ipcpath="/Users/aeufemio/tmp/.testethereum/geth.ipc" --rpcport "8080" --maxpeers "5" --networkid "47" --unlock "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22" --etherbase "0" --cache "1024" --password "/Users/aeufemio/tmp/.testethereumpass" --verbosity "0" --vmdebug $*
